export const LOGGED_USER_DETAILS = "LOGGED_USER_DETAILS";
export const PROPOSAL_IMAGES = "PROPOSAL_IMAGES";
export const PROPOSAL_SIDEBAR_DATA = "PROPOSAL_SIDEBAR_DATA";
export const SELECTED_CHAT = "SELECTED_CHAT";
export const CHATS = "CHATS";
export const NOTIFICATION = "NOTIFICATION";
